[package]
name = "power-applet"
version = "0.1.0"
edition = "2021"

[dependencies]
power-daemon = { version = "*", path = "../power-daemon", features = [
    "client",
] }
tokio = { version = "1.40.0", features = ["full"] }
