[package]
name = "frontend-gtk"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
power-daemon = { version = "0.1.0", path = "../power-daemon", features = [
    "client",
] }
relm4 = "0.9.0"
tokio = { version = "1.39.2", features = ["full"] }
