title: Power Options
description: A blazingly fast and feature-rich power management tool for Linux.
theme: just-the-docs

url: https://thealexdev23.github.io

aux_links:
  Power Options repository: https://github.com/thealexdev23/power-options